# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClassPlugin
                                 A QGIS plugin
 plugin generique
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Gérôme PECHEUR
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtGui import QGuiApplication
from qgis.PyQt.QtWidgets import  QLineEdit, QComboBox, QDateEdit
from qgis.core import Qgis,QgsProject,QgsApplication
from qgis.utils import plugins

import xml.etree.ElementTree as ET
from collections import Counter

from .assistant_hydro_dialog import ClassPluginDialog
import os.path

from .modele import *
from .fonction import *
from .mapping_version import *
from .window_manager import *

class ClassPlugin:
    """QGIS Plugin Implementation."""

    # dorénavant le "chemin le plus court" dépend du plugin "(IGN)chemin-le-plus-court"
    def runchepluscourt(self):
        try:
            processing_plugin = plugins[PLUGIN_CHE_PLUS_COURT]
            processing_plugin.run()
        except KeyError:
            QMessageBox.warning(None, "Attention",
                                f"Le plugin {PLUGIN_CHE_PLUS_COURT} n'est pas installé ou pas activé\n"
                                f"- Veuillez l'activer dans le menu \"Installer/Gérer les extensions de QGIS\"")

    def __init__(self, iface):

        # list contenant pour chaque tronçon un dictionnaire : clé = idchamps , val = attributs
        self.dico_champs_val_xml = {}
        self.list_dico_selection = []

        self.dico_champs_modifie = {}

        self.layer_hydro = None
        self.dlg = None
        self.iface = iface

        self.plugin_dir = os.path.dirname(__file__)

        self.dlgAProposDe = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__) , "aproposde.ui") ,self.dlgAProposDe)

    def valider(self):
        if len(self.dico_champs_modifie) == 0:
            return
        QGuiApplication.setOverrideCursor(WaitCursor)
        self.layer_hydro.startEditing()
        for sel in self.layer_hydro.selectedFeatures():
            # changement d'attributs par paquet (dico de valeurs)
            if not self.layer_hydro.changeAttributeValues(sel.id(), self.dico_champs_modifie):
                print("Erreur: changement d'attributs non effectués")
        QGuiApplication.restoreOverrideCursor()
        self.afficheMessageBar(
            f"Les modifications ont été effectués sur : {self.layer_hydro.selectedFeatureCount()} tronçon(s)")

    def afficheMessageBar(self, message):
        self.iface.messageBar().pushMessage("Info", message, level=Qgis.Info, duration=5)

    def getattributs_from_selection(self):
        self.list_dico_selection.clear()
        dico_tmp = {}

        for sel in self.layer_hydro.selectedFeatures():
            for idchamps in self.layer_hydro.fields():
                # TODO : on prend en compte tous les champs et non plus juste ceux du xml (combobox)
                # permet d'intégrer les lineedit et non plus que les combobox
                # if idchamps.name() in self.dico_champs_val_xml.keys():
                dico_tmp[self.layer_hydro.fields().indexOf(idchamps.name())] = sel[idchamps.name()]
            self.list_dico_selection.append(dico_tmp)

    def actualiserSelection(self):
        # cas de chargement d'un nouveau projet sans relancer qgis
        layer = QgsProject.instance().mapLayersByName(LAYER_HYDRO)
        if not layer:
            return

        # gestion de la couleur de selection
        couleur = self.dlg.mColorButton.color()
        self.iface.mapCanvas().setSelectionColor(couleur)

        nbsel = self.layer_hydro.selectedFeatureCount()
        self.dlg.labelNbSel.setText(f"<b>Sélection = <span style ='color: red'> {nbsel}</b></span>")

        if self.layer_hydro.selectedFeatureCount() == 2:
            self.dlg.pushButtonCheminCourt.setEnabled(True)
        else:
            self.dlg.pushButtonCheminCourt.setEnabled(False)

        if self.layer_hydro.selectedFeatureCount() == 0:
            self.vide_attribut_widgets()
            self.set_enable_widget(False)
        else:
            self.set_enable_widget(True)

        self.dlg.pushButtonValider.setEnabled(False)

        self.dico_champs_modifie.clear()
        self.init_widgets_from_selection()

        # récupérer les valeurs des attributs de toute la selection
        self.getattributs_from_selection()

    def apropos(self):
        self.dlgAProposDe.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
        self.dlgAProposDe.exec()


    def initGui(self):
        self.iface.projectRead.connect(self.on_project_opened)
        # événement fermeture de qgis
        QgsApplication.instance().aboutToQuit.connect(self.fermeture_qgis)

    def unload(self):
        pass

    def colorchange(self):
        # self.actualiserSelection()
        # self.iface.mapCanvas().refresh()
        couleur = self.dlg.mColorButton.color()
        self.iface.mapCanvas().setSelectionColor(couleur)

    def set_enable_widget(self, etat):
        for widget_interface in self.get_widgets("QLineEdit"):
            widget_interface.setEnabled(etat)
            if widget_interface.objectName() in LIST_LINEEDIT_READ_ONLY:
                widget_interface.setEnabled(False)

        for widget_interface in self.get_widgets("QComboBox"):
            widget_interface.setEnabled(etat)
            if widget_interface.objectName() in LIST_COMBOBOX_READ_ONLY:
                widget_interface.setEnabled(False)

    def widgetChange(self,widget_interface):
        if self.layer_hydro.selectedFeatureCount() == 0:
            return
        widget_interface.setStyleSheet(CUSTOM_WIDGETS[1])
        # self.dlg.pushButtonValider.setEnabled(True)

    def vide_attribut_widgets(self):
        for widget_interface in self.get_widgets("QLineEdit"):
            widget_interface.setText("")
            widget_interface.setStyleSheet(CUSTOM_WIDGETS[2])
        for widget_interface in self.get_widgets("QComboBox"):
            widget_interface.setCurrentIndex(0)
            widget_interface.setStyleSheet(CUSTOM_WIDGETS[2])

    # detection changement d'un combobox
    def combo_Change_utilisateur(self,widget_interface):
        index_champs = self.layer_hydro.fields().indexOf(widget_interface.objectName())
        valeur = widget_interface.currentText()
        if valeur == "Non":
            valeur = 0
        elif valeur == "Oui":
            valeur = 1
        self.dico_champs_modifie[index_champs] = valeur
        for sel in self.list_dico_selection:
            # pas de reel changement (re selection de l'attribut de la selection
            if sel[index_champs] == valeur:
                widget_interface.setStyleSheet(CUSTOM_WIDGETS[0])
            else:
                # self.dico_champs_modifie[index_champs] = valeur
                widget_interface.setStyleSheet(CUSTOM_WIDGETS[1])

        if self.ischangements():
            self.dlg.pushButtonValider.setEnabled(True)
            # widget_interface.setStyleSheet(CUSTOM_WIDGETS[1])
        else:
            self.dlg.pushButtonValider.setEnabled(False)
            # widget_interface.setStyleSheet(CUSTOM_WIDGETS[0])

    # changement de date du QDateEdit
    def on_date_changed(self,date):
        print("Nouvelle date :", date.toString("dd/MM/yyyy"))


    # detection changement d'un lineedit
    def lineedit_Change_utilisateur(self,widget_interface):
        index_champs = self.layer_hydro.fields().indexOf(widget_interface.objectName())
        if widget_interface.text() == "":
            self.dico_champs_modifie[index_champs] = "NULL"

        # on affecte ici meme si pas de changements, car si on modifie puis si
        # on revient à la valeur initiale, le dernier changement n'est pas pris en compte
        # pb : ça modifie la valeur meme si pas de changements.
        self.dico_champs_modifie[index_champs] = widget_interface.text()
        for sel in self.list_dico_selection:
            # pas de reel changement (re selection de l'attribut de la selection
            if sel[index_champs] == widget_interface.text():
                widget_interface.setStyleSheet(CUSTOM_WIDGETS[0])
            else:
                widget_interface.setStyleSheet(CUSTOM_WIDGETS[1])
        if self.ischangements():
            self.dlg.pushButtonValider.setEnabled(True)
            # widget_interface.setStyleSheet(CUSTOM_WIDGETS[1])
        else:
            self.dlg.pushButtonValider.setEnabled(False)
            # widget_interface.setStyleSheet(CUSTOM_WIDGETS[0])

    def ischangements(self):
        for sel in self.list_dico_selection:
            for index,valeur in sel.items():
                # try : si l'index n'existe pas dans le dico (il existe que si la valeur est modifiée)
                try:
                    if self.dico_champs_modifie[index] != valeur:
                        return True
                except KeyError:
                    pass
        return False

    def init_widgets_from_selection(self):
        self.vide_attribut_widgets()

        # COMBOBOX
        list_attr = []
        for widg in self.get_widgets("QComboBox"):
            list_attr.clear()
            widg.setStyleSheet(CUSTOM_WIDGETS[2])
            for sel in self.layer_hydro.selectedFeatures():
                try:
                    list_attr.append(str(sel[widg.objectName()]))
                    if str(widg.objectName()) in LIST_COMBO_BOOLEEN:
                        list_attr = ["Non" if val == "0" else "Oui" if val == "1" else val for val in list_attr]
                except KeyError:
                    pass
            """"***************
            traitement des occurrences pour recherche des attributs communs
            ****************"""
            compte = Counter(list_attr)
            for elem, count in compte.items():
                if count == self.layer_hydro.selectedFeatureCount():
                    widg.setCurrentText(list_attr[0])
                    widg.setStyleSheet(CUSTOM_WIDGETS[0])

        # LINEEDIT
        for widg in self.get_widgets("QLineEdit"):
            list_attr.clear()
            widg.setStyleSheet(CUSTOM_WIDGETS[2])
            for sel in self.layer_hydro.selectedFeatures():
                list_attr.append(sel[widg.objectName()])

            """"***************
            traitement des occurence pour recherche des attributs communs
            ****************"""
            compte = Counter(list_attr)
            for elem, count in compte.items():
                # toutes valeurs identiques (=valeurs communes)
                if count == self.layer_hydro.selectedFeatureCount():
                    # en vert
                    widg.setText(str(list_attr[0]))
                    if list_attr[0] != "NULL":
                        # en vert
                        widg.setStyleSheet(CUSTOM_WIDGETS[0])
                    else:
                        # pas de fond
                        widg.clear()
                        widg.setStyleSheet(CUSTOM_WIDGETS[2])
                else:
                    widg.setStyleSheet(CUSTOM_WIDGETS[2])

        # CALENDRIER
        # for widg in self.get_widgets("QDateEdit"):
        #     list_attr.clear()
        #     widg.setStyleSheet(CUSTOM_WIDGETS[2])
        #     # for sel in self.layer_hydro.selectedFeatures():
        #     #     # list_attr.append(sel[widg.objectName()])

    # retourne la liste des widgets dans le gridlayout
    def get_widgets(self, type_widget):
        list_combo = []
        list_line_edit = []
        list_label = []
        # pas utilisé, car pas demandé dans le cahier des charges
        list_date_edit = []

        widgets = self.dlg.children()
        for widg in widgets:
            if widg.objectName() == "gridLayoutWidget":
                children = widg.children()
                for child in children:
                    if type_widget == "QLineEdit"  and isinstance(child, QLineEdit):
                        list_line_edit.append(child)
                    elif type_widget == "QComboBox" and isinstance(child, QComboBox):
                        list_combo.append(child)
                    elif type_widget == "QLabel" and isinstance(child, QLabel):
                        list_label.append(child)
                    elif type_widget == "QDateEdit" and isinstance(child, QDateEdit):
                        list_date_edit.append(child)

        tmp = list_line_edit + list_combo + list_label + list_date_edit
        return tmp

    # initialise tous les combobox avec les attributs issus du xml
    # et return : le dictionnaire
    # clé : champs
    # valeur = tous les attributs possibles
    def init_widgets_from_xml(self):
        # parcours des widgets combobox inclu dans le formLayouWidget
        # et remplissage d'une liste de QComboBox

        list_widget = self.get_widgets("QComboBox")

        # initialisation du dictionnaire des champs, attributs associés
        # à partir du xml
        self.dico_champs_val_xml = {}
        tree = ET.parse(os.path.join(PATH_REP, "XML","Attributs.xml"))
        root = tree.getroot()
        for champs in root.findall("champs"):
            # il faut réinitialiser la liste, pas juste la vider
            list_valeur = []
            champs_id = champs.get('id')
            for valeur in champs.findall("valeur"):
                list_valeur.append(valeur.text)
            self.dico_champs_val_xml[champs_id] = list_valeur

        # initialisation des combo a vide
        for champs, valeur in self.dico_champs_val_xml.items():
            for widg in list_widget:
                if champs == widg.objectName():
                    widg.clear()

        # comparaison entre les CComboBox de l'interface et ceux du xml
        # et remplissage des combos
        for champs, valeur in self.dico_champs_val_xml.items():
            for widg in list_widget:
                if champs == widg.objectName():
                    widg.addItems(valeur)

    def islayer_espaceco(self):
        project = QgsProject.instance()
        if not project.fileName():
            QMessageBox.warning(None, "Avertissement", "<b>Veuillez charger un projet</b>")
            return False

        text = "La couche suivante n'est pas accessible :<br>"
        isok = True

        layer = project.mapLayersByName(LAYER_HYDRO)
        if not layer:
            text += f"<b>{LAYER_HYDRO}</b><br>"
            isok = False
        if not isok:
            QMessageBox.warning(None,"Avertissement",text)
            return False
        else:
            layer = project.mapLayersByName(LAYER_HYDRO)
            self.layer_hydro = layer[0]
            return True

    def on_sens_num(self):
        try:
            processing_plugin = plugins[PLUGIN_SENS_NUM]
            processing_plugin.run()
        except KeyError:
            QMessageBox.warning(None, "Attention",
                                f"Le plugin {PLUGIN_SENS_NUM} n'est pas installé ou pas activé\n"
                                f"- Veuillez l'activer dans le menu \"Installer/Gérer les extensions de QGIS\"")


    def affiche_spec(self,attribute):
        import webbrowser
        url = f"https://bdtopoexplorer.ign.fr/?id_theme=40&id_classe=44#attribute_{attribute}"
        webbrowser.open(url)

    def affiche_spec_code_hydro(self):
        import webbrowser
        url = "https://bdtopoexplorer.ign.fr/?attr_communs_theme=Hydrographie#attribute_296"
        webbrowser.open(url)

    def on_project_opened(self):
        settings = QSettings(NativeFormat, UserScope, "IGN", TITRE)
        visible = settings.value("visible", False, type=bool)
        if visible:
            self.run()

    def on_dialog_closed(self):
        # on deconnecte le signal en quittant
        try:
            self.iface.mapCanvas().selectionChanged.disconnect(self.actualiserSelection)
        except TypeError:
            pass  # aucune connexion existante

        # si on quitte, on remet la vue sans le sens de numérisation via le plugin
        try:
            processing_plugin = plugins[PLUGIN_SENS_NUM]
            processing_plugin.suppr_symb_sens_num(self.layer_hydro)
        except:
            pass
        self.layer_hydro.triggerRepaint()
        self.dlgAProposDe.close()
        sauve_position_dial(self.dlg)
        self.dlg = None

    def fermeture_qgis(self):
        sauve_position_dial(self.dlg)

    def run(self):
        if self.dlg is not None and self.dlg.isVisible():
            return

        self.dlg = ClassPluginDialog()
        self.dlg.setWindowTitle(f"{TITRE}")
        self.dlgAProposDe.setWindowTitle(f"{TITRE}")
        self.dlgAProposDe.pushButtonAffichedoc.clicked.connect(afficheDoc)

        # est-ce que les layer de l'espace co sont disponibles
        if not self.islayer_espaceco():
            return

        # connection de la fermeture du dialogue
        self.dlg.finished.connect(self.on_dialog_closed)
        restore_position_dial(self.dlg)

        # ******************************
        champs_manquant, champs_readonly = test_modele(self.layer_hydro)
        self.dlg.pushButton_warning.clicked.connect(lambda: config_modele(champs_manquant, champs_readonly))
        # self.dlg.pushButton_warning.hide()
        if len(champs_manquant) == 0:
            self.dlg.pushButton_warning.setStyleSheet("qproperty-icon: none;")
        # ******************************

        self.dlg.mColorButton.colorChanged.connect(self.colorchange)
        self.dlg.mColorButton.setColor(self.iface.mapCanvas().selectionColor())

        for widget_interface in self.get_widgets("QLabel"):
            widget_interface.setStyleSheet(CUSTOM_WIDGETS[4])
            if widget_interface.objectName() in LIST_LABEL_BLOC1:
                widget_interface.setStyleSheet(CUSTOM_WIDGETS[5])
            if widget_interface.objectName() in LIST_LABEL_BLOC2:
                widget_interface.setStyleSheet(CUSTOM_WIDGETS[6])

        # PAS UTILISE
        # initialisation à la date actuelle
        # self.dlg.date_de_validation_bcae.setDate(QDate.currentDate())
        # # événement du QDateEdit
        # self.dlg.date_de_validation_bcae.dateChanged.connect(self.on_date_changed)

        # événement des widgets
        # for widget_interface in self.get_widgets("QLineEdit"):
        #     widget_interface.textChanged.connect(lambda _, w1=widget_interface: self.widgetChange(w1))
        # for widget_interface in self.get_widgets("QComboBox"):
        #     widget_interface.currentTextChanged.connect(lambda _, w2=widget_interface: self.widgetChange(w2))

        # modif par l'utilisateur line edit
        for widget_interface in self.get_widgets("QLineEdit"):
            # textedited : changement par l'utilisateur, donc autre que par setText()
            widget_interface.textEdited.connect(lambda _, w3=widget_interface: self.lineedit_Change_utilisateur(w3))

        #  modif par l'utilisateur combobox
        for widget_interface in self.get_widgets("QComboBox"):
            widget_interface.activated.connect(lambda _, w3=widget_interface: self.combo_Change_utilisateur(w3))
            # widget_interface.currentTextChanged.connect(lambda _, w3=widget_interface: self.combo_Change_utilisateur(w3))

        # boutons des spécs
        self.dlg.pushButtonSpecNature.clicked.connect(lambda:self.affiche_spec("337"))
        self.dlg.pushButtonSpecFosse.clicked.connect(lambda:self.affiche_spec("340"))
        self.dlg.pushButtonSpecPosSol.clicked.connect(lambda:self.affiche_spec("338"))
        self.dlg.pushButtonSpecPersistance.clicked.connect(lambda: self.affiche_spec("339"))
        self.dlg.pushButtonSpecOrigine.clicked.connect(lambda: self.affiche_spec("345"))
        self.dlg.pushButtonSpecSens.clicked.connect(lambda: self.affiche_spec("347"))
        self.dlg.pushButtonSpecTypeBras.clicked.connect(lambda: self.affiche_spec("351"))
        self.dlg.pushButtonSpecDelimitation.clicked.connect(lambda: self.affiche_spec("349"))
        self.dlg.pushButtonSpecCodeHydro.clicked.connect(self.affiche_spec_code_hydro)
        self.dlg.pushButtonSpecInvenPE.clicked.connect(lambda: self.affiche_spec("361"))
        self.dlg.pushButtonSpecIdentPE.clicked.connect(lambda: self.affiche_spec("362"))

        self.dlg.pushButtonValider.clicked.connect(self.valider)
        self.dlg.pushButtonValider.setStyleSheet(CUSTOM_WIDGETS[3])

        # sens de numérisation
        self.dlg.pushButton_sens_num.clicked.connect(self.on_sens_num)

        self.dlg.pushButtonAPropos.clicked.connect(self.apropos)
        if self.layer_hydro.selectedFeatureCount() != 2:
            self.dlg.pushButtonCheminCourt.setEnabled(False)
        self.dlg.pushButtonCheminCourt.clicked.connect(self.runchepluscourt)

        # initialisation des widget ccombobox avec xml
        self.init_widgets_from_xml()

        self.layer_hydro.saveNamedStyle(os.path.join(PATH_REP, "sauvegarde_style_initial.qml"))

        self.iface.mapCanvas().selectionChanged.connect(self.actualiserSelection)
        self.actualiserSelection()

        # show the dialog
        self.dlg.setParent(self.iface.mainWindow())
        self.dlg.setWindowFlags(Dialog | WindowTitleHint | WindowCloseButtonHint)
        self.dlg.show()
        # Run the dialog event loop
        # result = self.dlg.exec()
        # See if OK was pressed
        # if not result:
            # # on deconnecte le signal en quittant
            # try:
            #     self.iface.mapCanvas().selectionChanged.disconnect(self.actualiserSelection)
            # except TypeError:
            #     pass  # aucune connexion existante
            #
            # # si on quitte, on remet la vue sans le sens de numérisation via le plugin
            # try:
            #     processing_plugin = plugins[PLUGIN_SENS_NUM]
            #     processing_plugin.suppr_symb_sens_num(self.layer_hydro)
            # except:
            #     pass
            # self.layer_hydro.triggerRepaint()
            # self.dlgAProposDe.close()
